#!/bin/bash

# NodeBB 双方案 SSO 自动化配置脚本
# 适用于 macOS / Linux

set -e

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# 项目路径
NODEBB_PATH="/Users/admin/ma jia/NodeBB"
YUDAO_PATH="/Users/admin/ma jia/ruoyi-vue-pro"

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}        NodeBB 双方案 SSO 自动化配置脚本${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"

# 检查必要工具
check_command() {
    if ! command -v $1 &> /dev/null; then
        return 1
    fi
    return 0
}

echo -e "${YELLOW}📋 检查必要工具...${NC}"
check_command node || { echo -e "${RED}❌ 错误: node 未安装${NC}"; exit 1; }
check_command npm || { echo -e "${RED}❌ 错误: npm 未安装${NC}"; exit 1; }

# psql 可选，如果没有则提供手动执行 SQL 的说明
PSQL_AVAILABLE=0
if check_command psql; then
    echo -e "${GREEN}✅ psql 已安装${NC}"
    PSQL_AVAILABLE=1
else
    echo -e "${YELLOW}⚠️  psql 未安装，将提供手动执行 SQL 的说明${NC}"
fi
echo -e "${GREEN}✅ 工具检查完成${NC}\n"

# 步骤 1: 执行建表SQL
echo -e "${YELLOW}📊 步骤 1/5: 数据库建表...${NC}"
read -p "数据库类型 (postgres/mysql): " DB_TYPE
read -p "数据库名: " DB_NAME

if [ "$DB_TYPE" = "postgres" ]; then
    SQL_FILE="$YUDAO_PATH/sql/postgresql/member_nodebb_user.sql"
    if [ $PSQL_AVAILABLE -eq 1 ]; then
        echo -e "${BLUE}正在执行 SQL...${NC}"
        psql -U postgres -d $DB_NAME -f "$SQL_FILE"
        echo -e "${GREEN}✅ PostgreSQL 建表完成${NC}\n"
    else
        echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo -e "${YELLOW}请手动执行以下 SQL 文件：${NC}"
        echo -e "${BLUE}$SQL_FILE${NC}"
        echo -e ""
        echo -e "${YELLOW}方式1 - 使用 PostgreSQL GUI 工具（推荐）：${NC}"
        echo -e "  1. 打开 pgAdmin / TablePlus / DataGrip"
        echo -e "  2. 连接到数据库: $DB_NAME"
        echo -e "  3. 打开并执行: $SQL_FILE"
        echo -e ""
        echo -e "${YELLOW}方式2 - 使用 NodeBB 内置 PostgreSQL 连接：${NC}"
        echo -e "  使用下方生成的脚本"
        echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        
        # 生成通过 NodeBB 连接执行 SQL 的脚本
        cat > "$NODEBB_PATH/create-nodebb-table.js" << 'SQLSCRIPT'
const nconf = require('nconf');
const path = require('path');
const fs = require('fs');

nconf.argv().env({ separator: '__' });
nconf.file({ file: path.join(__dirname, 'config.json') });
nconf.defaults({ base_dir: __dirname });

const db = require('./src/database');

async function createTable() {
  console.log('连接数据库...');
  await db.init();
  
  const sql = `
CREATE TABLE IF NOT EXISTS member_nodebb_user (
    id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id int8 NOT NULL,
    nodebb_uid int4 DEFAULT NULL,
    username varchar(255) DEFAULT NULL,
    sync_status int2 DEFAULT 0,
    sync_error_msg varchar(500) DEFAULT NULL,
    creator varchar(64) DEFAULT '',
    create_time timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updater varchar(64) DEFAULT '',
    update_time timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted int2 DEFAULT 0 NOT NULL,
    tenant_id int8 DEFAULT 0 NOT NULL,
    CONSTRAINT pk_member_nodebb_user PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_user_id_deleted ON member_nodebb_user (user_id, deleted);
CREATE INDEX IF NOT EXISTS idx_nodebb_uid ON member_nodebb_user (nodebb_uid);
  `;
  
  console.log('执行建表 SQL...');
  await db.pool.query(sql);
  console.log('✅ 表创建成功！');
  
  await db.close();
  process.exit(0);
}

createTable().catch(err => {
  console.error('❌ 建表失败：', err);
  process.exit(1);
});
SQLSCRIPT
        
        echo -e ""
        echo -e "${GREEN}✨ 已生成建表脚本：${NC}"
        echo -e "${BLUE}$NODEBB_PATH/create-nodebb-table.js${NC}"
        echo -e ""
        echo -e "${YELLOW}执行方式：${NC}"
        echo -e "${BLUE}cd \"$NODEBB_PATH\" && node create-nodebb-table.js${NC}"
        echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo -e ""
        read -p "按回车键继续（确认已执行 SQL）..." CONTINUE
    fi
elif [ "$DB_TYPE" = "mysql" ]; then
    SQL_FILE="$YUDAO_PATH/sql/mysql/member_nodebb_user.sql"
    if check_command mysql; then
        read -p "MySQL 用户名: " MYSQL_USER
        mysql -u $MYSQL_USER -p $DB_NAME < "$SQL_FILE"
        echo -e "${GREEN}✅ MySQL 建表完成${NC}\n"
    else
        echo -e "${YELLOW}⚠️  mysql 命令不可用，请手动执行 SQL：${NC}"
        echo -e "${BLUE}$SQL_FILE${NC}"
        read -p "按回车键继续（确认已执行 SQL）..." CONTINUE
    fi
else
    echo -e "${RED}❌ 不支持的数据库类型${NC}"
    exit 1
fi

# 步骤 2: 配置 Session Sharing
echo -e "${YELLOW}🔐 步骤 2/5: 配置 Session Sharing (方案A)...${NC}"
echo -e "正在生成 JWT Secret..."

# 生成随机 JWT Secret
JWT_SECRET=$(openssl rand -base64 48)
echo -e "${GREEN}✨ JWT Secret 已生成: $JWT_SECRET${NC}"

# 保存到 NodeBB
cd "$NODEBB_PATH"
node -e "
const nconf = require('nconf');
const path = require('path');
nconf.file({ file: path.join(__dirname, 'config.json') });
const db = require('./src/database');

async function saveConfig() {
  await db.init();
  await db.setObjectField('settings:session-sharing', 'secret', '$JWT_SECRET');
  await db.setObjectField('settings:session-sharing', 'cookie', 'token');
  await db.setObjectField('settings:session-sharing', 'cookieDomain', '');
  console.log('✅ Session Sharing 配置已保存');
  await db.close();
  process.exit(0);
}
saveConfig().catch(err => { console.error(err); process.exit(1); });
" 2>/dev/null

echo -e "${GREEN}✅ Session Sharing 配置完成${NC}\n"

# 步骤 3: 生成 Master Token
echo -e "${YELLOW}🔑 步骤 3/5: 生成 Master Token...${NC}"
echo -e "${BLUE}请按照以下步骤手动操作：${NC}"
echo -e "1. 访问: http://localhost:4567/admin/settings/api"
echo -e "2. 点击 ${GREEN}Generate Token${NC} → 选择 ${GREEN}Master Token${NC}"
echo -e "3. 复制生成的 Token\n"
read -p "请输入 Master Token: " MASTER_TOKEN
echo -e "${GREEN}✅ Master Token 已保存${NC}\n"

# 步骤 4: 配置 OAuth2
echo -e "${YELLOW}🌐 步骤 4/5: 配置 OAuth2 (方案B)...${NC}"

read -p "OAuth2 Client Secret (留空使用默认): " OAUTH_SECRET
OAUTH_SECRET=${OAUTH_SECRET:-nodebb-secret-123}

echo -e "\n${BLUE}请在 ruoyi 后台执行以下 SQL:${NC}"
echo -e "${YELLOW}────────────────────────────────────────${NC}"
cat << EOF
INSERT INTO system_oauth2_client (
  client_id, secret, name, logo, description,
  status, access_token_validity_seconds, refresh_token_validity_seconds,
  redirect_uris, authorized_grant_types, scopes, auto_approve_scopes,
  creator, create_time, updater, update_time, deleted, tenant_id
) VALUES (
  'nodebb', '$OAUTH_SECRET', 'NodeBB Forum', '', 'NodeBB 论坛 SSO',
  0, 604800, 2592000,
  '["http://localhost:4567/auth/nodebb/callback"]',
  '["authorization_code","refresh_token"]',
  '["user.read"]', '["user.read"]',
  '1', NOW(), '1', NOW(), 0, 1
);
EOF
echo -e "${YELLOW}────────────────────────────────────────${NC}\n"

read -p "SQL 已执行完成？ (y/n): " SQL_DONE
if [ "$SQL_DONE" != "y" ]; then
    echo -e "${RED}❌ 请先执行 SQL 后再继续${NC}"
    exit 1
fi

# 配置 NodeBB OAuth2 插件
cd "$NODEBB_PATH"
node -e "
const nconf = require('nconf');
const path = require('path');
nconf.file({ file: path.join(__dirname, 'config.json') });
const db = require('./src/database');

async function configureOAuth() {
  await db.init();
  
  const config = {
    id: 'nodebb',
    name: 'RuoYi Member',
    type: 'oauth2',
    oauth2: {
      authorizationURL: 'http://localhost:8080/admin-api/system/oauth2/authorize',
      tokenURL: 'http://localhost:8080/admin-api/system/oauth2/token',
      clientID: 'nodebb',
      clientSecret: '$OAUTH_SECRET',
      scope: 'user.read',
      userRoute: 'http://localhost:8080/app-api/member/oauth2/user'
    },
    userRoute: 'http://localhost:8080/app-api/member/oauth2/user',
    emailClaim: 'email',
    usernameClaim: 'username'
  };
  
  await db.setObject('settings:sso-oauth', config);
  console.log('✅ OAuth2 配置已保存');
  await db.close();
  process.exit(0);
}
configureOAuth().catch(err => { console.error(err); process.exit(1); });
" 2>/dev/null

echo -e "${GREEN}✅ OAuth2 配置完成${NC}\n"

# 步骤 5: 生成 yudao 配置
echo -e "${YELLOW}⚙️  步骤 5/5: 生成 yudao 配置文件...${NC}"

CONFIG_FILE="$YUDAO_PATH/yudao-server/src/main/resources/application-nodebb.yaml"

cat > "$CONFIG_FILE" << EOF
# NodeBB 双方案 SSO 配置
# 此文件由自动化脚本生成于 $(date)

yudao:
  member:
    nodebb:
      # ========== 基础配置 ==========
      enabled: true
      url: http://localhost:4567
      
      # ========== 方案A: Session Sharing ==========
      sso-secret: "$JWT_SECRET"
      sso-cookie-name: token
      sso-cookie-domain: ""
      sso-cookie-max-age-seconds: 604800
      
      # ========== NodeBB API ==========
      master-token: "$MASTER_TOKEN"
      admin-uid: 1
      default-password: "DefaultPass123!"
EOF

echo -e "${GREEN}✅ 配置文件已生成: $CONFIG_FILE${NC}"
echo -e "\n${BLUE}请在 application-local.yaml 中添加:${NC}"
echo -e "${YELLOW}spring:${NC}"
echo -e "${YELLOW}  profiles:${NC}"
echo -e "${YELLOW}    include: nodebb${NC}\n"

# 重启服务提示
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}🎉 配置完成！${NC}\n"

echo -e "${YELLOW}📋 下一步操作：${NC}"
echo -e "1. 重启 NodeBB:"
echo -e "   ${BLUE}cd $NODEBB_PATH && ./nodebb restart${NC}"
echo -e "\n2. 重启 yudao:"
echo -e "   ${BLUE}cd $YUDAO_PATH/yudao-server && mvn clean package -DskipTests && java -jar target/*.jar${NC}"
echo -e "\n3. 测试两种方案:"
echo -e "   - 方案A: 从 ruoyi 调用 /member/auth/nodebb-sso 跳转"
echo -e "   - 方案B: 直接访问 http://localhost:4567 点击登录"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

echo -e "\n${GREEN}✨ 配置脚本执行完成！${NC}\n"
echo -e "${BLUE}详细文档: $YUDAO_PATH/yudao-module-member/NodeBB-Dual-SSO-Integration.md${NC}\n"

