-- ----------------------------
-- Table structure for member_children
-- 会员模块 - 儿童个人信息表（自闭症互助平台）
-- ----------------------------
CREATE TABLE IF NOT EXISTS member_children (
    id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id int8 NOT NULL,
    nickname varchar(50) NOT NULL DEFAULT '',
    avatar_url varchar(512) DEFAULT '',
    gender varchar(10) NOT NULL DEFAULT 'unknown',
    age_years int2,
    age_group varchar(20) DEFAULT '',
    diagnosis_date timestamp,
    guardian_relation varchar(20) DEFAULT '',
    status_tags varchar(2000) DEFAULT '[]',
    goal_tags varchar(2000) DEFAULT '[]',
    description varchar(500) DEFAULT '',
    creator varchar(64) DEFAULT '',
    create_time timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updater varchar(64) DEFAULT '',
    update_time timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted int2 DEFAULT 0 NOT NULL,
    tenant_id int8 DEFAULT 0 NOT NULL,
    CONSTRAINT pk_member_children PRIMARY KEY (id)
);

COMMENT ON TABLE member_children IS '会员模块 - 儿童个人信息表';
COMMENT ON COLUMN member_children.id IS '自增主键';
COMMENT ON COLUMN member_children.user_id IS '关联用户ID（监护人）';
COMMENT ON COLUMN member_children.nickname IS '孩子昵称';
COMMENT ON COLUMN member_children.avatar_url IS '孩子头像地址';
COMMENT ON COLUMN member_children.gender IS '性别：male-男性，female-女性，unknown-未知';
COMMENT ON COLUMN member_children.age_years IS '实际年龄（岁）';
COMMENT ON COLUMN member_children.age_group IS '年龄组：0-3 / 3-6 / 6-12 / 12+';
COMMENT ON COLUMN member_children.diagnosis_date IS '诊断日期';
COMMENT ON COLUMN member_children.guardian_relation IS '监护人关系：father-父亲，mother-母亲，grandfather-祖父，grandmother-祖母，other-其他';
COMMENT ON COLUMN member_children.status_tags IS '状态标签（JSON数组）：例如 ["LANGUAGE_DELAY", "SOCIAL_DIFFICULTY", "SENSORY_SENSITIVITY", "REPETITIVE_BEHAVIOR"]';
COMMENT ON COLUMN member_children.goal_tags IS '目标标签（JSON数组）：例如 ["LANGUAGE_MIMIC", "KINDERGARTEN_PREP", "SOCIAL_SKILLS", "DAILY_LIVING"]';
COMMENT ON COLUMN member_children.description IS '备注说明';
COMMENT ON COLUMN member_children.creator IS '创建者';
COMMENT ON COLUMN member_children.create_time IS '创建时间';
COMMENT ON COLUMN member_children.updater IS '更新者';
COMMENT ON COLUMN member_children.update_time IS '更新时间';
COMMENT ON COLUMN member_children.deleted IS '是否删除：0-未删除，1-已删除';
COMMENT ON COLUMN member_children.tenant_id IS '租户编号';

-- 索引
CREATE INDEX IF NOT EXISTS idx_member_children_user_id ON member_children (user_id, deleted);
CREATE INDEX IF NOT EXISTS idx_member_children_age_group ON member_children (age_group);
CREATE INDEX IF NOT EXISTS idx_member_children_create_time ON member_children (create_time);

