-- ----------------------------
-- Table structure for member_nodebb_user
-- 会员用户 - NodeBB 用户映射表
-- ----------------------------
CREATE TABLE IF NOT EXISTS member_nodebb_user (
    id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id int8 NOT NULL,
    nodebb_uid int4 DEFAULT NULL,
    nodebb_username varchar(255) DEFAULT NULL,
    sync_status int2 NOT NULL DEFAULT 0,
    sync_error_msg varchar(500) DEFAULT NULL,
    creator varchar(64) DEFAULT '',
    create_time timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updater varchar(64) DEFAULT '',
    update_time timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted int2 DEFAULT 0 NOT NULL,
    tenant_id int8 DEFAULT 0 NOT NULL,
    CONSTRAINT pk_member_nodebb_user PRIMARY KEY (id)
);

COMMENT ON TABLE member_nodebb_user IS '会员用户 - NodeBB 用户映射表';
COMMENT ON COLUMN member_nodebb_user.id IS '自增主键';
COMMENT ON COLUMN member_nodebb_user.user_id IS '会员用户 ID';
COMMENT ON COLUMN member_nodebb_user.nodebb_uid IS 'NodeBB 用户 UID';
COMMENT ON COLUMN member_nodebb_user.nodebb_username IS 'NodeBB 用户名';
COMMENT ON COLUMN member_nodebb_user.sync_status IS '同步状态：1-成功，0-失败';
COMMENT ON COLUMN member_nodebb_user.sync_error_msg IS '同步失败原因';
COMMENT ON COLUMN member_nodebb_user.creator IS '创建者';
COMMENT ON COLUMN member_nodebb_user.create_time IS '创建时间';
COMMENT ON COLUMN member_nodebb_user.updater IS '更新者';
COMMENT ON COLUMN member_nodebb_user.update_time IS '更新时间';
COMMENT ON COLUMN member_nodebb_user.deleted IS '是否删除';
COMMENT ON COLUMN member_nodebb_user.tenant_id IS '租户编号';

-- 索引
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_id_deleted ON member_nodebb_user (user_id, deleted);
CREATE INDEX IF NOT EXISTS idx_nodebb_uid ON member_nodebb_user (nodebb_uid);

